### ISSUE TITLE
`queue_runner` uses `this` after destruction

### ISSUE THREAD

**Issue by Kirkezz** [Jaskowicz1/rconpp#13]
I am using your library as follows:
```
int getPlayersCount() {
    static int id = 2;
    int result = -1;

    rconpp::rcon_client client(rcon_credentials.ip, rcon_credentials.port, rcon_credentials.password);
    if (client.connected) {
        auto response = client.send_data_sync("list", ++id, rconpp::data_type::SERVERDATA_EXECCOMMAND);
        /* ... */
        std::cout << response.data << std::endl;
    }

    return result;
}
```
The program crashes with segfault:
![crash](https://github.com/Jaskowicz1/rconpp/assets/87193614/072bc480-276d-432e-8e7f-7080e77eab5c)
I think the problem is that `queue_runner` uses `this` after the rcon_client object is destroyed.
With the following changes, segfault no longer occurs:
![changes](https://github.com/Jaskowicz1/rconpp/assets/87193614/a6d9128f-4d0b-4628-93d3-06a85ef8ccc7)

**Comment by Jaskowicz1** [comment]
Huh, that is a bizarre one. the deconstructor of rcon_client should kill this queue_runner (as connected becomes false so the while should break).

If that does fix the issue though, I'll gladly add it! Thank you!!

**Comment by Kirkezz** [comment]
I think the UB still persists here. The problem is that `connected` becomes `false` in the middle of a while loop. It also looks like `queue_runner` is not joinable in destructor.

**Comment by Jaskowicz1** [comment]
> I think the UB still persists here. The problem is that `connected` becomes `false` in the middle of a while loop. It also looks like `queue_runner` is not joinable in destructor.

Hm, that's interesting... Odd why this never came up in testing 🤔

**Comment by Jaskowicz1** [comment]
ahhhhhh I'm so silly, I understand now.
